 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Boeing 737-800                                              
     # Surfaces =  11
     # Strips   = 137
     # Vortices =1505

  Sref =  1260.0       Cref =  11.000       Bref =  113.00    
  Xref =  65.269       Yref =  0.0000       Zref =  1.1656    

 Standard axis orientation,  X fwd, Z down         

 Run case: -unnamed-                               

  Alpha =   1.91840     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.700     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.00770     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.54449     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.54444
  CDtot =   0.01053
  CDvis =   0.00000     CDind = 0.0105289
  CLff  =   0.54551     CDff  = 0.0100678    | Trefftz
  CYff  =  -0.00000         e =    0.9284    | Plane  

   slat            =   0.00000
   flap            =   0.00000
   aileron         =   0.00000
   elevator        =   0.89680
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   7.299206    CLb =   0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -1.326015
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.276089
 y  mom.  Cm |    Cma =  -1.884644    Cmb =  -0.000000
 z' mom.  Cn'|    Cna =  -0.000000    Cnb =   0.244427

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  22.200703    CLr =  -0.000000
 y  force CY |    CYp =   0.079192    CYq =   0.000000    CYr =   1.047402
 x' mom.  Cl'|    Clp =  -0.570732    Clq =  -0.000000    Clr =   0.226779
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -84.906515    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.034837    Cnq =  -0.000000    Cnr =  -0.491477

                  slat         d1     flap         d2     aileron      d3     elevator     d4     rudder       d5 
                  ----------------    ----------------    ----------------    ----------------    ----------------
 z' force CL |   CLd1 =  -0.001260   CLd2 =   0.036081   CLd3 =  -0.000000   CLd4 =   0.015022   CLd5 =   0.000000
 y  force CY |   CYd1 =   0.000000   CYd2 =  -0.000000   CYd3 =   0.000139   CYd4 =  -0.000000   CYd5 =  -0.009405
 x' mom.  Cl'|   Cld1 =   0.000000   Cld2 =   0.000000   Cld3 =   0.002762   Cld4 =  -0.000000   Cld5 =  -0.000993
 y  mom.  Cm |   Cmd1 =  -0.001052   Cmd2 =   0.023079   Cmd3 =   0.000000   Cmd4 =  -0.071575   Cmd5 =  -0.000000
 z' mom.  Cn'|   Cnd1 =  -0.000000   Cnd2 =   0.000000   Cnd3 =   0.000178   Cnd4 =   0.000000   Cnd5 =   0.004367
 Trefftz drag| CDffd1 =  -0.000033 CDffd2 =   0.001432 CDffd3 =   0.000000 CDffd4 =   0.000542 CDffd5 =   0.000000
 span eff.   |    ed1 =  -0.001004    ed2 =  -0.008885    ed3 =  -0.000000    ed4 =   0.001075    ed5 =   0.000000



 Neutral point  Xnp =  68.108784

 Clb Cnr / Clr Cnb  =   2.447930    (  > 1 if spirally stable )
